name = "24payshop"
main = "24payshop.js"
compatibility_date = "2026-06-01"

routes = [
  { pattern = "24payshop.com", custom_domain = true },
  { pattern = "www.24payshop.com", custom_domain = true }
]
